<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.entity_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an Entity Test module.') . '</p>';
      return $output;

    default:
  }

  /**
   * Impliment hook_theme().
   */
  function entity_test_theme($existing, $type, $theme, $path) {
    return [
      'entity_test_myInfo' => [
         'variables' => ['myInfo' => NULL, 'target' => NULL,
         'overridden' => FALSE],

        ],

    ];
  }
}